### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by klinic** [cyrilzakka/MAE3D#1]
Hi, Thank you for your work!

Which dataset should I download to start training？Kinetics-400 or ImageNet？

and where can I get "ledger.csv"?

**Comment by klinic** [comment]
and where can I get "ledger.csv"

**Comment by cyrilzakka** [comment]
Hey!

The repository currently only supports 3D inputs, so using the ImageNet dataset is not possible. I’ll be working on adding image support soon.

I haven’t personally used Kinetics, but as long as you organize the dataset in the manner outlined in the README, it should work fine. ‘ledger.csv’ is simply a file you create with rows containing each video_name, start_frame, end_frame and class/pseudoclass.

**Comment by klinic** [comment]
Hello, senior. 

What dataset did you train on?  >_<

**Comment by cyrilzakka** [comment]
I’ve amassed a dataset of videos for personal use.

**Comment by klinic** [comment]
Thank you for your replying!

So I will use public dataset. >_<
