### ISSUE TITLE
About Finetuning Code

### ISSUE THREAD

**Issue by likemby** [cyrilzakka/MAE3D#2]
In terms of MAE code, yours is the most concise, readable and highly referential I've seen. I hope to continue referring to your code for the fine-tuning section.
If it is not convenient to upload now, send it to my email address. Thank you!!!

**Comment by likemby** [comment]
my email MaBingyang.chn@outlook.com

**Comment by cyrilzakka** [comment]
Thank you for the feedback! I'll be releasing it (and more) in the coming weeks!
